//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _69CSI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class associate_member
    {
        public Nullable<decimal> slno { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string memberno { get; set; }
        public string designation { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string phone1 { get; set; }
        public string mobile { get; set; }
        public string age { get; set; }
        public string sex { get; set; }
        public string dob { get; set; }
        public string spouse { get; set; }
        public string qualification { get; set; }
        public string answer { get; set; }
        public string question { get; set; }
        public string last_date { get; set; }
        public string pin { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public long ID { get; set; }
    }
}
