//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _69CSI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conference
    {
        public long CId { get; set; }
        public string Day { get; set; }
        public string CDate { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string Hall { get; set; }
        public string Details { get; set; }
        public int Status { get; set; }
    }
}
