//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _69CSI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class csi_massmail_member
    {
        public int Sl { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string memberno { get; set; }
        public string emailid { get; set; }
    }
}
