//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _69CSI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class csi_mail_details
    {
        public int SL { get; set; }
        public Nullable<System.DateTime> Mail_Dt { get; set; }
        public string Mail_Sender { get; set; }
        public string Mail_Body { get; set; }
        public string Mail_Sub { get; set; }
    }
}
