//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _69CSI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CSI_69_Con_Accompanys
    {
        public long AccompanyId { get; set; }
        public long RegId { get; set; }
        public string Name { get; set; }
        public long Age { get; set; }
        public string Sex { get; set; }
        public string Meal_Preference { get; set; }
        public string Accommodation { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public string Check_in_Time { get; set; }
        public string Check_out_Time { get; set; }
        public Nullable<long> Extra1 { get; set; }
        public Nullable<System.DateTime> Extra2 { get; set; }
        public string Extra3 { get; set; }
        public string Extra4 { get; set; }
        public string Extra5 { get; set; }
        public Nullable<long> Extra6 { get; set; }
        public Nullable<System.DateTime> Extra7 { get; set; }
        public string Extra8 { get; set; }
        public string Extra9 { get; set; }
        public string Extra10 { get; set; }
    
        public virtual tbl_CSI_69_Con_RegistrationDetails tbl_CSI_69_Con_RegistrationDetails { get; set; }
    }
}
