//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _69CSI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBlog
    {
        public long BlogId { get; set; }
        public string BlogTitle { get; set; }
        public string BlogDetails { get; set; }
        public string MemberId { get; set; }
        public string AuthorName { get; set; }
        public System.DateTime PostedDate { get; set; }
        public string Mnth { get; set; }
        public string Yr { get; set; }
        public int Status { get; set; }
    }
}
