//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _69CSI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoginDetail
    {
        public long Id { get; set; }
        public string MemberId { get; set; }
        public string Fullname { get; set; }
        public System.DateTime LoginDate { get; set; }
    }
}
