//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _69CSI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblregid
    {
        public long id { get; set; }
        public string regid { get; set; }
        public string imeino { get; set; }
        public string SENDER_ID { get; set; }
        public string membershipNo { get; set; }
        public string mobileNo { get; set; }
    }
}
