//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _69CSI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wbc_NonCsiMembers
    {
        public long UserId { get; set; }
        public string FullName { get; set; }
        public string Password { get; set; }
        public string EmailId { get; set; }
        public string PharmaName { get; set; }
        public string UserName { get; set; }
        public string WebcastName { get; set; }
        public string Mobile { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Status { get; set; }
        public long Extra1 { get; set; }
        public long Extra2 { get; set; }
        public string Extra3 { get; set; }
        public string Extra4 { get; set; }
        public string Extra5 { get; set; }
    }
}
