//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _69CSI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wbc_CsiMembersLoginDtls
    {
        public long Id { get; set; }
        public string Memberno { get; set; }
        public string WebcastName { get; set; }
        public System.DateTime LastLogin { get; set; }
        public string Mnth { get; set; }
        public string Yr { get; set; }
        public Nullable<long> Extra1 { get; set; }
        public long Extra2 { get; set; }
        public string Extra3 { get; set; }
        public string Extra4 { get; set; }
        public string Extra5 { get; set; }
    }
}
